name: Django CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install system dependencies for Pillow
        run: sudo apt-get install -y libjpeg-dev zlib1g-dev libpng-dev libtiff-dev libfreetype6-dev

      - name: Apply migrations
        run: python manage.py migrate

      - name: Run tests
        env:
          DEBUG: True
          SECRET_KEY: test
        run: python manage.py test
